#!/usr/bin/env sh

req_file=${1:-requirements.txt}
env_name_default=${PWD##*/}-env  # use directory name by stripping longest prefix
env_name=${2:-$env_name_default}
python -m venv "$env_name"
. "$env_name/bin/activate"
pip install -r "$req_file"
activate_name=activate-$env_name
ln -sf "$env_name/bin/activate" "$activate_name"  # clobbers!

printf -- "----------------------------------------\n"
printf "Created environment in $env_name\n"
printf "To activate,\n  . \"$activate_name\"\n"
printf -- "----------------------------------------\n"
